#pragma once

#define LED_CAPS_LOCK_PIN   B12
#define LED_PIN_ON_STATE    0

#define LED_LAYER_PIN       B13

#define SPLIT_HAND_PIN B0
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_LAYER_LED

#define USB_VBUS_PIN B14

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN A9
#define SERIAL_USART_RX_PIN A10

#define ENCODER_A_PINS { B9 }
#define ENCODER_B_PINS { B8 }
#define ENCODER_RESOLUTIONS { 2 }
#define ENCODER_DEFAULT_POS 0x3
